### ISSUE TITLE
API is very slow

### ISSUE THREAD

**Issue by mazipan** [agallio/ina-covid-bed#12]
I know the origin application by Kemenkes was very slow.

But when try to improve the experience from the existing applications, it's better to not just improve the UI but also improve the speed.

Some of recommendation:
- Cache the API for 5-10 minute
- Serve static data and add a cronjob to update the latest static data in every 5-10 minutes

5-10 minutes is just an estimation, if you afraid with the data validity, just start with a very short time, if you think okay, you can increase the cache expiration along the way.

**Comment by agallio** [comment]
I've been thinking about this too. Currently the endpoint is only guard by `cache-control` like this code:

https://github.com/agallio/ina-covid-bed/blob/ea97bd07a1d0226cab7f8be70655897d6267a434/pages/api/bed.js#L283

Maybe to fix this I should increase the `max-age`? Or any ideas how to handle the cache properly inside Next.js API routes?

**Comment by yogiw** [comment]
I think we can directly cache the response from Kemenkes (storing in an object or using library like node-cache)
https://github.com/agallio/ina-covid-bed/blob/5aff6d49776441b663240b4c6c72fc8f47e81407/pages/api/bed.js#L281

**Comment by agallio** [comment]
Could you elaborate more @yogiwisesa? I think there are 2 options, `node-cache` & `memory-cache`. But I'm not sure how to implement either of those two things.

**Comment by mazipan** [comment]
Memory Cache in many cases will not help in the serverless environment.
Since it will utilize the global object that should exist as long as the server is up.

But it just my assumption 😂

You need to double check it first

**Comment by agallio** [comment]
New references
https://leerob.io/blog/serverless-redis-nextjs
