### ISSUE TITLE
Fix dark mode contrast on href links & buttons

### ISSUE THREAD

**Issue by agallio** [agallio/ina-covid-bed#31]
## Description

Fix dark mode contrast on href links & buttons.

<img width="382" alt="Screen Shot 2021-07-09 at 18 38 00" src="https://user-images.githubusercontent.com/22767465/125072620-00c56080-e0e5-11eb-8658-8ba1b7ba0077.png">

## Expected Behaviour

Make the links and buttons more contrast to the users. Use [WCAG color contrast tool](https://chrome.google.com/webstore/detail/wcag-color-contrast-check/plnahcmalebffmaghcpcmpaciebdhgdf) to check the contrast.

**Comment by ekafyi** [comment]
May I take this one?

Also shall I also fix contrast for input text and placeholder or do I need to open a separate issue?

![🇮🇩_INA_COVID_BED](https://user-images.githubusercontent.com/6597211/125174309-9862a600-e1ee-11eb-9383-b9d43d56bdad.png)
