### ISSUE TITLE
Add back to homepage button from map page

### ISSUE THREAD

**Issue by agallio** [agallio/ina-covid-bed#36]
## Description

Add back to homepage button from map page.

**Comment by syauqy** [comment]
Hi @agallio, which one do you prefer?

![image](https://user-images.githubusercontent.com/3627108/126064894-66da0fd1-aaeb-4f8d-9f07-36e0c7731403.png) ![image](https://user-images.githubusercontent.com/3627108/126064956-1a9e9e12-e696-4bfb-a15e-307e5535a59f.png)

Or do you have any preferences on the back button placement?

**Comment by agallio** [comment]
Hi @syauqy,

Hmmm, how about something like this? (From [this link](https://jakarta-vax-availability.vercel.app/map))

![image](https://user-images.githubusercontent.com/22767465/126065227-475a8fe4-5ad2-41e9-839f-945abb354840.jpeg)

**Comment by syauqy** [comment]
Sure @agallio. 
But the existing search bar `SearchProvince.js` is used on both the homepage and map page. 

Should I create a copy component with the back button or just add the back button on `SearchProvince.js` and add a prop to hide the back button while on the homepage?

**Comment by agallio** [comment]
Yeah, I think just add the back button into the `SearchProvince` component, and then add a prop called `backButton` with boolean value. When the `backButton` prop value is true then show the back button.
