### ISSUE TITLE
Make links in mapbox feature box (hospital info) more prominent

### ISSUE THREAD

**Issue by ekafyi** [agallio/ina-covid-bed#39]
## Description

Currently the hotline link and the detail (Siranap) link are styled like the surrounding text. Users may not be aware these are clickable.

![current UI](https://user-images.githubusercontent.com/6597211/125175583-6d308480-e1f7-11eb-8b4c-67eff8fede80.png)

Proposed feature: make the links more prominent so users are aware of the possible actions.

![Screen Shot 2021-07-11 at 03 17 00](https://user-images.githubusercontent.com/6597211/125175646-b4b71080-e1f7-11eb-841e-ce0d51bfc4b7.png)

## Implementation Model

Modify the markup and either inline the new CSS styles or add them to global CSS

Happy to submit PR if this is considered necessary. Other UI suggestions welcome.

**Comment by agallio** [comment]
Closed by #40.
