### ISSUE TITLE
Some Province can't reload

### ISSUE THREAD

**Issue by yudimarta** [agallio/ina-covid-bed#41]
## Description

**Getting Error on params prov=jawa_timur, jawa_barat, jawa_tengah :**

An error occurred with your deployment

**FUNCTION_INVOCATION_TIMEOUT**

**Comment by codingki** [comment]
I assume this is a BE or API Endpoint issue @agallio did you already investigate on the BE side?

**Comment by agallio** [comment]
This issue is coming from Vercel. In the free plan, Vercel limits the timeout of every API endpoint to only 10s. When the data is too large, the API endpoint returns the data at above 10s.

I don't have enough time to check at this moment. So that's why this issue was labelled `help wanted`.

**Comment by agallio** [comment]
This project is now transferred to a pro Vercel account. So, hopefully this issue won't happen again.

**Comment by yudimarta** [comment]
Thank You, already check and back to normal.
