### ISSUE TITLE
Add info text when API doesn't response after 10s

### ISSUE THREAD

**Issue by agallio** [agallio/ina-covid-bed#44]
## Description

Add info text when API doesn't yet response after 10s. Because right now, API response is being cache for only 5 minutes. When the cache expires, users have to get the data directly from the API endpoint that scrape SIRANAP page. Because of the large dataset these provinces listed below is very slow to scrape:

- `jawa_barat`: `9s-11s`
- `banten`: `8s-12s`
- `jawa_tengah`: `10s-15s`
- `jawa_timur`: `10s-12s`

Without the info text, users doesn't know that this loading gonna resolve at the end.

## Implementation Model

Add info text in the loading screen, at the bottom of the loading animation. The info text would be something like "Pengambilan data memerlukan waktu yang lebih lama. Mohon tunggu" or if you have any idea on how to say that we're needed more time to fetch data, just comment.

**Comment by syauqy** [comment]
Hi @agallio is it okay to use `useEffect` hook with `timeout` to make the timer for the text visibility?
Do you have any suggestion?
![ina bed timeout](https://user-images.githubusercontent.com/3627108/126281600-1f8a7d4b-2fa5-447a-a87d-6f7db63463d4.gif)

**Comment by agallio** [comment]
Resolved by #49.
