### ISSUE TITLE
Add SEO

### ISSUE THREAD

**Issue by agallio** [agallio/ina-covid-bed#9]
## Description

Add basic SEO such as opengraph image, title, description. So when users share the link it shows some useful information.

## Implementation Model

Maybe we can use [next-seo](https://github.com/garmeeh/next-seo) or we can add them natively with Next.js `<Head>` component.

**Comment by galihlprakoso** [comment]
We have two pages right:
1. The home with big search province input screen.
2. List of available beds in each hospitel screen.

I did some research on Google Trends. [https://trends.google.com/trends/explore?q=rujukan%20covid,rumah%20sakit%20covid,rumah%20sakit%20corona,rumah%20sakit%20covid%2019](url)

It shows that `rumah sakit covid` and `rujukan covid` having a great popularity (100 points and 60). How about using the `rumah sakit covid` as our primary keyword and `rujukan covid` secondary so:
1. on home page the keyword would be `rumah sakit covid` and `rujukan covid`.
2. on search result page same, but add dynamic province name.

**Comment by galihlprakoso** [comment]
I'll do this ga. So the primary goal is not to compete on SERP right? only to `show useful information` when user share?

**Comment by agallio** [comment]
Yes! Exactly. I'll assign this to you mas, thanks 🙇🏻

**Comment by galihlprakoso** [comment]
Lekk goo 🚀🚀

**Comment by agallio** [comment]
@galihlprakoso opengraph images.

- Opengraph Main (`/`, `/[province]`)
![Main](https://user-images.githubusercontent.com/22767465/124880669-b8c90f80-dff8-11eb-8d7a-94a848ff2951.png)

- Opengraph Map (`/map`)
![Map](https://user-images.githubusercontent.com/22767465/124880648-b666b580-dff8-11eb-8334-3ad3f3ebb6c3.png)
